variables:
  FILE_PATH: /usr/local/deploy/
  HELM_CHART_PATH: spring-helm-chart

stages:
  - deploy-cp

deploy-cp:
  stage: deploy-cp
  script:
    - rm -r $FILE_PATH$HELM_CHART_PATH
    - cp ./$HELM_CHART_PATH $FILE_PATH$HELM_CHART_PATH
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  tags:
    - master-shell